Fixes a problem with python2.6
Previously it failed with:

/home/ondrej/repos/femhub/local/lib/python2.6/site-packages/sage/interfaces/expect.pyc in __init__(self, name, prompt, command, server, server_tmpdir, ulimit, maxread, script_subdirectory, restart_on_ctrlc, verbose_start, init_code, max_startup_time, logfile, eval_using_file_cutoff, do_cleaner, remote_cleaner, path)
    210         quit.expect_objects.append(weakref.ref(self))
    211         self._available_vars = []
--> 212         ParentWithBase.__init__(self, self)
    213
    214     def _get(self, wait=0.1, alternate_prompt=None):

TypeError: object.__init__() takes no parameters

when executing:

from sage.server.notebook.notebook_object import notebook

on startup of spd.